/**:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    path: "/home/ares/ares/src/2.mp4"
    frame_rate: 60
    start_frame: 0
    frame_id: "camera_optical_frame"
    keep_looping: true              #是否循环播放
